#spring.application.name=final-project-java

server:
  port: 8181

spring:
  application:
    name: final-project-java
  datasource:
    url: jdbc:mysql://spring-database.cb6kkieswnlv.ap-northeast-2.rds.amazonaws.com:3306/plugngo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: plugngo
    password: final
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: update
      database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1?? ??? ?? ???
      max-request-size: 20MB # ?? ??? ?? ???

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html

jwt:
  secret: w9uTOtlPQvRzj7vv6FmF3/2K79DHTFsjUfQ2BDyoYwlGIUhze3cPG7zgq9DYq4sWpk05RGsVIdEXiZNgfIdiVw==

request:
  permit-all-patterns:
    - /
    - /car/**
    - /api/auth/**
    - /api/board/list
    - /api/board/detail/**
    - /login/**
    - /charge/**

# kakao login
kakao:
  client_id: c5dad018ecb6e841a078eaf95dc88336
  redirect_url: http://localhost:3000/oauth/kakao
  client_secret: eanoHKJ7M6Z0vKpHsHSj1eqNkhNECVBK

# naver login
naver:
  client_id: Gjv33ITkKHcgByVmXeCs
  redirect_url: http://localhost:3000/oauth/naver
  client_secret: h40BqSHUw0

message:
  API_KEY: NCS65OKWNUYJ571O
  SECRET_KEY: KBIXE9FNNESONSCWWZXZJA0Q3NVYZQGO























































